services:
  postgres:
    image: postgres:16
    container_name: agenda_postgres
    restart: always
    environment:
      POSTGRES_DB: bd_apiagenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kaio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: